### ISSUE TITLE
Failed to resolve host name updates.jenkins-ci.org

### ISSUE THREAD

**Issue by LnAlex** [cloudbees/jenkins-ci.org-docker#57]
After starting the container, the webpage is correctly reachable but when I want to update the plugins, Jenkins throws me that : 

    Checking internet connectivity
    Checking update center connectivity
    Failed to resolve host name updates.jenkins-ci.org. Perhaps you need to configure HTTP proxy?

    java.net.UnknownHostException: updates.jenkins-ci.org
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	at java.net.Socket.connect(Socket.java:579)
    	at java.net.Socket.connect(Socket.java:528)
    	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
    	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
    	at hudson.model.UpdateCenter$UpdateCenterConfiguration.testConnection(UpdateCenter.java:872)
    	at hudson.model.UpdateCenter$UpdateCenterConfiguration.checkUpdateCenter(UpdateCenter.java:710)
    	at hudson.model.UpdateCenter$ConnectionCheckJob.run(UpdateCenter.java:1045)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:104)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by mekdev** [comment]
Guy did you figure out what was the cause of this ?
The ticket was closed by op without updates.
Is it a misconfiguration in docker somewhere ?

Thank you!

**Comment by LnAlex** [comment]
Misconfiguration with Docker and the firewall.

**Comment by abhashar** [comment]
Hi LnAlex,

Will it be possible for you to provide more information on this issue? How did you solve it?

p.s: I am an ex-employee of Atos, India and worked for the AWL project. It is a small world!

**Comment by abhashar** [comment]
I was connected to my VPN, hence it wasn't working for me. I disconnected and now I am no longer facing any issues.

**Comment by LnAlex** [comment]
Small world indeed !

That's quite a long time, It was a misconfiguration with my iptables rules on my server and port binding with my container. I did not remember how I fixed it exactly (it was my first times with Docker therefore I was not very clever to using it).

**Comment by brennonobst** [comment]
I started the docker container as instructed with no configuration to speak of and see this error not sure what inside docker needs to be configured. Maybe can someone put it with the instructions?
Instructions - https://hub.docker.com/_/jenkins/
$ docker run -p 8080:8080 -p 50000:50000 jenkins

---Log----
Installing Plugins/Upgrades
Preparation	
Checking internet connectivity
Checking update center connectivity
Failed to resolve host name updates.jenkins-ci.org. Perhaps you need to configure HTTP proxy?
java.net.UnknownHostException: updates.jenkins-ci.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.testConnection(UpdateCenter.java:1143)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.checkUpdateCenter(UpdateCenter.java:953)
	at hudson.model.UpdateCenter$ConnectionCheckJob.run(UpdateCenter.java:1360)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Thread.java:745)

**Comment by carlossg** [comment]
there's nothing to be configured by default, your docker host needs to have internet access and the right dns config

**Comment by yedaodao** [comment]
@lnalex You should re-run your jenkins images with parameter "--dns 8.8.8.8". Additional, don't forget to back up your jenkins data if you didn't mount a volume.

**Comment by lleirgarciaboadapruebas** [comment]
@yedaodao worked fine on my container jenkins! great!

**Comment by fengerzh** [comment]
`service docker restart` solved the problem.

**Comment by mohammedazhar7** [comment]
docker restart worked for me

**Comment by mahaodong6318** [comment]
> `service docker restart` solved the problem.

no docker

**Comment by jcabelloc** [comment]
Hi There. After trying different things, these commands worked for me:

Disable and stop the firewall on my Centos Host
`sudo systemctl disable firewalld`
`sudo systemctl stop firewalld`

Then, restart docker

    `sudo service docker restart`

I hope it works for you.

**Comment by chandan607** [comment]
Hi There, this means your firewall is blocking the traffic , this can be solved in various way like :
1. Add proxy details if you are using a proxy server to manage traffic (like in any organization)
2. If you are working your personal machine  add the Add Jenkins application to the list( in windows Windows security>Firewall and network protection > add an app through firewall)  or 
3. disable the firewall 
Hope this works :)

**Comment by thirupathib12** [comment]
> `service docker restart` solved the problem.

Thanks it worked for me...

**Comment by srisrimani88** [comment]
i tried by disconnecting vpn and its worked for me.

**Comment by MasterCrake** [comment]
I just want to add that I got the same issue after the update url changed from https://updates.jenkins.io/update-center.json to https://updates.jenkins.io/current/update-center.json. There seems to be a redirect in place but my Jenkins instance received a 301 instead.

**Comment by lemeurherve** [comment]
> There seems to be a redirect in place but my Jenkins instance received a 301 instead.
Which is expected, as [301 means "Moved permanently"](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301), with the new location in the response headers.

**Comment by MasterCrake** [comment]
Sorry, I think the issue for me is somewhere in my k3s cluster. It seems like none of the pods are able to resolve DNS currently. At first I thought Jenkins interpreted 301 as a failure as I received UnknownHostException but it is definitely something else that has gone wrong in the cluster.

**Comment by Tejas-Valame** [comment]
I has the same problem
You can use the --dns flag when running a container
Try using this
`
docker run --rm --dns 8.8.8.8 -p 8080:8080 -p 50000:50000 -d -v jenkins_home:/var/jenkins_home jenkins/jenkins
`

Hope this solves the issue

**Comment by marytlf** [comment]
> `service docker restart` solved the problem.

It worked for me as well, but I lost the images that was downloaded, just keep it in mind in case you cannot lose your data.
